as yet unclassified
introduction
^HelpTopic title:'Introduction' contents: 
'
Some words about this project 
-----------------------------
Morphic is the main GUI API used by the majority of Pharo code. This documentation is neither official or finished in any way. Like you I am a Pharo begineer but because there is very little documnetation on Morphic I decided to write my own with the hope that others will find helpfull. This documentation is a companion to my video tutorials on Morphic you can find in my youtube channel. I welcome any correction and recommendation in the github repo of the project. '